doctest for '0-add_integer.py' file

Import the function
  >>> add_integer = __import__("0-add_integer").add_integer

Check for module and function docstrings
  >>> mod = __import__("0-add_integer").__doc__
  >>> len(mod) > 1
  True
  >>> fxn = __import__("0-add_integer").add_integer.__doc__
  >>> len(fxn) > 1
  True

Regular additions
  >>> add_integer(3, 5)
  8

  >>> add_integer(-3, 5)
  2

  >>> add_integer(3, -5)
  -2

  >>> add_integer(-3, -5)
  -8

  >>> add_integer(3)
  101

  >>> add_integer(-2)
  96

  >>> [add_integer(x, x * 2) for x in range (5)]
  [0, 3, 6, 9, 12]

  >>> add_integer(999999999999999999, 1)
  1000000000000000000

Floats addition
  >>> add_integer(3.2, 5)
  8

  >>> add_integer(3, 2.1)
  5

  >>> add_integer(-3.2, 5.5)
  2
  
Too Many/No Arguments
  >>> add_integer()
  Traceback (most recent call last):
  ...
  TypeError: add_integer() missing 1 required positional argument: 'a'

  >>> add_integer(2, 3, 4, 5)
  Traceback (most recent call last):
  ...
  TypeError: add_integer() takes from 1 to 2 positional arguments but 4 were given

Boolean Parameters
  >>> add_integer(True, 5)
  Traceback (most recent call last):
  ...
  TypeError: a must be an integer

  >>> add_integer(2, False)
  Traceback (most recent call last):
  ...
  TypeError: b must be an integer

Non integer parameters
  >>> add_integer("hi")
  Traceback (most recent call last):
  ...
  TypeError: a must be an integer

  >>> add_integer(1, "hi")
  Traceback (most recent call last):
  ...
  TypeError: b must be an integer

  >>> add_integer(None)
  Traceback (most recent call last):
  ...
  TypeError: a must be an integer

  >>> add_integer(float('nan'))
  Traceback (most recent call last):
  ...
  ValueError: cannot convert float NaN to integer

  >>> add_integer(10, float('inf'))
  Traceback (most recent call last):
  ...
  OverflowError: cannot convert float infinity to integer

  >>> add_integer([1,2,3], 4)
  Traceback (most recent call last):
  ...
  TypeError: a must be an integer

  >>> add_integer((10,), {"key": "value"})
  Traceback (most recent call last):
  ...
  TypeError: a must be an integer
